### ISSUE TITLE
[Request] Clarification on clients in custom.json

### ISSUE THREAD

**Issue by OMEGARAZER** [mdhiggins/PlexAutoSkip#10]
Looking for help/clarification on where to locate or confirm the URL to use in the clients section of custom.json

I have a WebOS TV that locks up, for lack of a better term, after playing an episode and having the intro skipped. The episode ends as normal but I need to restart the tv to get any control back. So was looking to just deny it from the script.

currently, my config has:
```
"clients": {
    "PC": "http://192.168.1.2:32500",
    "iPhone": "http://192.168.1.3:32500",
    "TV": "http://192.168.1.8:32500"
},
```
and has `"clients": [ "TV" ],` in the blocked section but it's still skipping the intro on all devices.

Thanks in advance for any help.

**Comment by mdhiggins** [comment]
Is your client name actually `TV`? The client name isn't arbitrary; it needs to match what the player is defined as within the Plex app

Additionally unless you're getting errors and need to override the IP address and port you probably don't need to define the client IP addresses and may actually introduce errors if those IP addresses change in the future, can probably remove all those definitions; certain players don't even support IP based seeking so you might be breaking them by forcing IP based seeking (web players for example)

Easiest way to confirm your player name is to look at the logs when it performs a seek, you should see something like

`Seeking Plex for iOS player playing 317 [435] (Bob's Burgers s03e18 - It Snakes a Village) Michael’s iPhone from 18 to 20000`

Where `Michael's iPhone` is the player name in this example

**Comment by mdhiggins** [comment]
I added some clarification on the wiki regarding client definitions

**Comment by OMEGARAZER** [comment]
> Is your client name actually `TV`? The client name isn't arbitrary; it needs to match what the player is defined as within the Plex app

Yeah, probably should have thought of that but saw both sections and thought they needed to be defined in there. Thanks.
