### ISSUE TITLE
Request: Custom markers for skipping outro

### ISSUE THREAD

**Issue by saivajr** [mdhiggins/PlexAutoSkip#11]
First of all, thanks for the good work. I am using the containerized version and it works perfectly! 

One thing that would greatly improve upon the existing features would be to allow "negative" values for the custom markers. For example, most shows have the same outro sequence so we could essentially add to the custom.json markers for specific shows / seasons to skip to the next episode when there is X amount of milliseconds left.

**Comment by mdhiggins** [comment]
3f53fefee8d0ce7111d05eaa17e9c18c34baa771

That should do it

If you set `start` to `0` it will assume the start as before, but setting `end` to `0` will assume the full duration of the media

Here's a sample that skips the first 20 seconds and the last 20 seconds

```json
    "markers": {
        "tmdb://32726": [
            {
                "start": 0,
                "end": 20000
            },
            {
                "start": -20000,
                "end": 0
            }
        ]
    },
```

**Comment by mdhiggins** [comment]
Additionally if plex adds any outro detection in the future that should already be supported by adding 'outro' or whatever equivalent to the `tags` option

I have seen some shows recently coming with an `End Credits` chapter so that can be added to the tags as well to skip that chapter

And finally there's the skip-last-chapter option which will skip the final chapter is present and it occurs within whatever final percentage of the media duration

So that should be a pretty robust set of outro options for you!

**Comment by saivajr** [comment]
Damn, that was quick. Thanks so much. It seems like the scheduled docker publish run missed your changes by about 30 minutes. Whenever you have a chance, could you do a manual run there?

Also I have one last question, would this skip to the next media item (episode), or to the end of the current episode? Cause plex has this annoying 10 seconds countdown which I think is not customizable. It would be nice to be able to just skip to the next episode without waiting for it.

**Comment by mdhiggins** [comment]
You can use the PAS_UPDATE environment variable and then just restart the container to get the latest git pull

For now it just seeks to the end but I can look into doing a "next" type command

**Comment by saivajr** [comment]
Ah nice, don't know how I missed that. That's great, works as expected now.

Yeah if you find any time to look into that it would be awesome. I think this is a separate request though, I will close this issue.

**Comment by mdhiggins** [comment]
170a7af2919620afa5e631354c28bc30fe5c2b38

Added a `next` option to the skip section that will mark the media as watched and trigger a 'skipNext' API call if the media its monitoring has reached its end or if the skip target is the end, default is False so set that True if you want that behavior

```ini
[Skip]
...
next = True
```

**Comment by saivajr** [comment]
Amazing, how kind of you! Thanks.. :)

**Comment by mdhiggins** [comment]
Let me know if there's any issues but it seems to be working on my testing

**Comment by saivajr** [comment]
I tested it as well. Works perfectly!
