### ISSUE TITLE
Ability customise skipping for specific shows

### ISSUE THREAD

**Issue by tom-dell** [mdhiggins/PlexAutoSkip#13]
Just wondering if it would be possible to have the ability to customise the skipping for shows?

For example, parks and rec has a obnoxious intro, but no outro, where as I would like to skip both on futurama. 

Hopefully i’m not asking too much lol

**Comment by mdhiggins** [comment]
You mean to have individual tags per show?

**Comment by mdhiggins** [comment]
Just to clarify. 

Plex does not have automatic outro detection and tagging so unless you were manually defining the outro times they won't be skipped until Plex adds that feature

Only situation you might want custom show tags I can think of is for media with labeled chapters that you only want to apply skipping to specific shows but not others

Can you clarify what you're requesting and the use case?

**Comment by cjmanca** [comment]
For any shows that have a pretty standard length outro, you can use the custom json files to set it to skip the outro for the whole show. For instance, I use this for Star Trek: TNG

```
{
    "markers": {
        "tvdb://71470": [
            {
                "start": -51000,
                "end": 0,
                "cascade": false
            }
        ]
    },
    "offsets": {},
    "allowed": {
        "users": [],
        "clients": [],
        "keys": []
    },
    "blocked": {
        "users": [],
        "clients": [],
        "keys": []
    },
    "clients": {}
}
```

I *think* you can prevent skipping per show with the "blocked" section, but I'm not 100% sure how to do that

**Comment by mdhiggins** [comment]
I still don't follow. Your custom defined outro will only apply to the show based on its tvdb ID. It should not apply to other shows 

You can filter out specific episodes or seasons within that show you don't wish to apply that outro to if there are exceptions, if that's what you mean. That's done using the cascade option and applying a more specific identifier. The bobs burger example in the wiki details this and shows an example.

If you mean you want to ignore skipping the auto detected markers for a show just add that to the blocked keys section. This is also outlined in the wiki with an example. 

Blocking a show season or episode will not block custom markers, just the auto detected content (intro for example)

**Comment by mdhiggins** [comment]
I did like the idea of custom tags for specific media so I added support for that as well with custom.json, just as an aside

https://github.com/mdhiggins/PlexAutoSkip/wiki/Configuration#tags-dict

**Comment by tom-dell** [comment]
That's exactly what I wanted

Parks and rec: Skip intro, don't skip outro
Futurama: Skip intro, skip outro

Thanks for putting it in so fast :)

**Comment by mdhiggins** [comment]
Again this update will not change anything unless you are custom labeling chapters. Outros are still not magically detected
