### ISSUE TITLE
Custom Offset Per Show (With Detected Intro)

### ISSUE THREAD

**Issue by ChipSkylark37** [mdhiggins/PlexAutoSkip#16]
There are some shows, such as OnePiece, that Plex Pass detects the intro for, but it doesn't detect the entire intro. There is approximately a 1.5 minute intro, which Plex / this skips automatically, but then it goes into this, which is always right after the intro skip which is another .5min:

https://www.youtube.com/watch?v=ZB8glS-FKjM

Is there a way to set an additional +30s skip for this show, regardless of when the intro actually starts? I took a look through the custom examples, but a little confused with how they work. I believe I would use something like this:

    "offsets": {
        "tmdb://37854: {
            "start": 2000,
            "end": 30000
        }
    }

If I understand the above, the 'start' will be automatically skip 2000ms after the 'Skip Intro' displays and then will also go 30000ms after the 'end' of the intro, which should be an additional +30s in this case?

**Comment by mdhiggins** [comment]
That looks correct. Is that not working for you?

**Comment by mdhiggins** [comment]
Missing a quote after the tmdb ID but assume that's just an example

**Comment by ChipSkylark37** [comment]
I think that may have been it - it's working now. I switched to using the rating key from the XML and when reloading I was getting illegal characters on lines. After fixing each of those its now working as expected.

I must have copied from a bad source - Thanks for the quick assist! 

Something perhaps for the future, if there would be a way to 'cancel' the auto-skip on a case by case basis (within that initial start offset period?). Sometimes I want to watch the intro, but 95% of the time I'd want it to auto-skip as intended. 

Either way, thanks for making this and helping out :)

**Comment by ChipSkylark37** [comment]
On another note, on the custom section with allow dicts and block dicts:

https://github.com/mdhiggins/PlexAutoSkip/wiki/Configuration#offsets-dict

Should the 'keys' under blocked read 'allowed' or 'blocked' ? It currently reads allowed.

"List of content identifiers blocked from using the autoskip feature, you can include GUID, ratingKey, parentRatingKeys to allow a season, or grandparentRatingKeys to allow an entire show"

**Comment by mdhiggins** [comment]
Just a typo from copy/pasting that reference, there is both an allowed and blocked option, updated the wiki to fix that; thanks

> Something perhaps for the future, if there would be a way to 'cancel' the auto-skip on a case by case basis (within that initial start offset period?). Sometimes I want to watch the intro, but 95% of the time I'd want it to auto-skip as intended.

With regards to this, I think that's probably the blocked feature you're talking about? You can't really stop the skipper on the fly per watch session since it has no interface (and there's no way to integrate into the plex interface to abort the auto skip) but you can block the auto skipper from running on certain media, users, or players
