### ISSUE TITLE
Reoccuring Error

### ISSUE THREAD

**Issue by irodimus** [mdhiggins/PlexAutoSkip#20]
I had this reoccurring error show up in the logs and I'm unsure if it causes any issues as the intros still seem to be skipped.

```
ERROR - Unexpected error getting data from session alert
Traceback (most recent call last):
  File "/Applications/Plex Scripts/Apps/PlexAutoSkip/resources/skipper.py", line 315, in processAlert
    self.media_sessions[sessionKey].updateOffset(media.viewOffset, seeking=False, state=state)
  File "/Applications/Plex Scripts/Apps/PlexAutoSkip/resources/mediaWrapper.py", line 223, in updateOffset
    self.log.debug("Updating session %s viewOffset %d, old %d, diff %d (%ds since last update)" % (self, offset, self.viewOffset, (offset - self.viewOffset), (datetime.now() - self.lastUpdate).total_seconds()))
  File "/Applications/Plex Scripts/Apps/PlexAutoSkip/resources/mediaWrapper.py", line 213, in viewOffset
    return vo if vo <= self.media.duration else self.media.duration
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
```

This is with Python 3.9.13 and the latest release of PlexAutoSkip as July 4. This error loops as video plays on the Plex server.

**Comment by mdhiggins** [comment]
Hm looks like your API is return None for the media duration

Not sure why it would be doing that, it shouldn't but this patch should at least handle those situations more gracefully

0cd4639bb25f958342e250b80c081717f3f2f18d

**Comment by mdhiggins** [comment]
c97130c8f3da4441dc5e05694ab1b857aa586cd0

Made a typo on that last commit, above fixes that
