### ISSUE TITLE
Auto-Skip no longer working

### ISSUE THREAD

**Issue by doctarrwho** [mdhiggins/PlexAutoSkip#22]
Since the update after issue #21 (including the update earlier today), there are no errors but auto skip doesn't work. Confirmed the issue on Apple TV as well as Shield Pro for multiple shows.

```
today at 9:32:12 PMINFO - Skipper initiated and ready
today at 9:39:43 PMINFO - Found new session 22................. viewOffset 0 ['xxxxxx'], sessions: 0
```

Rolling docker back to `ghcr.io/mdhiggins/plexautoskip-docker@sha256:553ebda88b91b7e312337b04272b34fc97264fb375e6e5685ef7984ed5470f76` with auto-update disabled fixes the issue.

**Comment by mdhiggins** [comment]
There was a bug with the API update. Should be fixed on latest

Did you see my last comment on that issue?

**Comment by doctarrwho** [comment]
I had tried after the latest update, and it didn't work. I'm going to test again shortly and let you know.

**Comment by doctarrwho** [comment]
It does work. The show that wasn't working seems to be missing intro markers. My bad!
