### ISSUE TITLE
Downloaded episodes aren't detected

### ISSUE THREAD

**Issue by Bart274** [mdhiggins/PlexAutoSkip#30]
When you download an episode on your ipad and play the media from the downloads, it's not detected by the software and the auto skip doesn't work. On the exact same device it works fine if you're streaming an episode.

**Comment by mdhiggins** [comment]
The whole script works by monitoring playback server side and then skipping during the correct time window. I imagine downloading the episode makes the server side activity disappear and the playback session invisible. No way around that

**Comment by mdhiggins** [comment]
Confirmed downloaded content is invisible to the server
