### ISSUE TITLE
Feature request : Credits detection auto skip

### ISSUE THREAD

**Issue by tchirou** [mdhiggins/PlexAutoSkip#31]
Hi
Plex has released the credit detection : https://support.plex.tv/articles/credits-detection/
Any chance you could implement the auto skip like with the intro ?
Thanks a lot for all your work

**Comment by mdhiggins** [comment]
Already supported. Just add "credits" to your tags

**Comment by tchirou** [comment]
Fantastic !
Thanks a lot
