### ISSUE TITLE
Disable intro/credit auto skip for first episode in current watch session.

### ISSUE THREAD

**Issue by ShanaryS** [mdhiggins/PlexAutoSkip#37]
This is so when you are binge watching a series, the intro/credits play on the first episode, but is auto skipped for the remainder of that session. I'm thinking if nothing from that series was played in the past 2 hours, it won't auto skip.

This is similar to the existing premier skips already in the script, but on a session by session basis. Is this possible?

**Comment by mdhiggins** [comment]
Not easily. Plex creates a new "session" every time a new episode starts so its not easy or reliable to track, so you'd need to craft backend tracking into the script to figure out what a session is and when to block skipping based on a per user/client basis, store that, and then reference it and clear it out when no longer relevant

Probably not something I would add but I'd take a look at a pull request

**Comment by ShanaryS** [comment]
Added a PR #38
