### ISSUE TITLE
Feature request: Managed users

### ISSUE THREAD

**Issue by knaackville** [mdhiggins/PlexAutoSkip#42]
Hey.  This is working fantastic on my server, so thank you very much for making this.

Is there a way to select which managed users are allowed or blocked from the autoskip feature?  The kids (which are managed users on the main account) enjoy the intro to their shows, but from what I can tell, I can only block users who have their own plex.tv account.

Thanks

**Comment by mdhiggins** [comment]
It goes by the username so I would think it wouldn't matter since I think the managed users still get unique usernames despite being under the umbrella of the main account, post some logs of the different users playing and I can take a look if its not working

**Comment by mdhiggins** [comment]
Made a quick managed account and can confirm that the username is appropriately reported and adding that username to the blocked list prevents autoskipping

**Comment by knaackville** [comment]
Ahh, I think that helped figure out my issue.  It seems that my local username for my PlexPass account doesn't work in the custom.json, but the plex.tv account name does.  And you're right that the managed users without accounts can be added with the local username.

In short, use plex.tv username when one exists (not local username), and use managed user username for managed accounts.

Thanks for testing, and all is good on my end.
