### ISSUE TITLE
Button Noise When Auto-Skipping

### ISSUE THREAD

**Issue by ChipSkylark37** [mdhiggins/PlexAutoSkip#43]
Commit: [ea37bfe]
Plex Client: Native Plex Client on nVidia Shield 8.2.3
Plex Server: Windows 10, 64 bit. 1.31.2.6810  

This has been occurring for the last few versions now, but as soon as the 'Skip Intro' button comes up, whether it's set to Auto-Skip or not, the nVidia sheild is making the 'button' noise as if you are pressing the OK button. It can make this noise 10-15 times before the auto-skip skips, or seemingly indefinitely if you don't have auto-skip enabled.

I've not changed anything with volume settings, though I know that is a feature to mute the intro.

Has anyone else experienced this or have any troubleshooting steps?

**Comment by AngusNB** [comment]
I have a Shield 2017 and have not had the issue.

**Comment by mdhiggins** [comment]
This might not have anything to do with plexautoskip. It doesn't simulate any button presses. Does shutting down PAS change anything?

**Comment by AngusNB** [comment]
It appears to be a Plex issue.
They have released an update, in beta, that identifies one of the fixes as;
[TV] Player: prevent focus noise from constantly occurring when skip intro is shown.

[Plex for Android 9.19.1.487-beta](https://forums.plex.tv/t/release-announcements-android-tv-beta/154124/604)

**Comment by ChipSkylark37** [comment]
That looks like it may have been it. 

I verified I was updated to the latest beta today and replayed a few of the ones that it was present on and I don't experience the issue anymore. 

Thanks!

I'd consider this closed.
