### ISSUE TITLE
Error - Error seeking (Shield Android TV 2017 and 2019) , unable to find player

### ISSUE THREAD

**Issue by BionicAlice** [mdhiggins/PlexAutoSkip#5]
Works great on web and IOS when tested with 2017 and a 2019 shield tv I got the following error when  testing:
Plex Player for 2017 and 2019 shield(9.0): 08.29.0.30180 
Plex server : windows 10 , 1.25.3.5409
Tested web and ios and shield with same file to make sure it was not the file. Tried other files as well on shield same result. 
I am guessing the plex api just doesn't work with shield? Or maybe due to the big 9.0 (android 11) update to all shields that got pushed yesterday.

> INFO - Seeking player SHIELD Android TV playing 78 [56258] (Family Guy s19e16 - Who's Brian Now?) SHIELD Android TV from 29474 to 31678
ERROR - Error seeking
Traceback (most recent call last):
  File "L:\PlexAutoSkip\resources\introSkipper.py", line 89, in seekTo
    player.seekTo(targetOffset)
  File "C:\Python3\lib\site-packages\plexapi\client.py", line 376, in seekTo
    self.sendCommand('playback/seekTo', offset=offset, type=mtype)
  File "C:\Python3\lib\site-packages\plexapi\client.py", line 231, in sendCommand
    return query(key, headers=headers)
  File "C:\Python3\lib\site-packages\plexapi\server.py", line 669, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (500) internal_server_error; https://192-168-1-10.178abf122e274a8e8db03b16517866ac.plex.direct:32400/player/playback/seekTo?commandID=52&offset=30678&type=video <?xml version='1.0' encoding='utf-8'?> <Response code="2000" status="FrameworkException: Unable to find player with identifier fd40d60186070e4e-com-plexapp-android">   <Traceback>Traceback (most recent call last):   File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f11334058\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 843, in handle_request     result = f(**d)   File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f11334058\System.bundle\Contents\Code\playerservice.py", line 50, in process_remote_command     raise FrameworkException('Unable to find player with identifier %s' % identifier) FrameworkException: Unable to find player with identifier fd40d60186070e4e-com-plexapp-android </Traceback> </Response>

**Comment by mdhiggins** [comment]
This looks like the same error for #3 let's consolidate discussion there
