### ISSUE TITLE
[FR] Skip back after skipping intro to fix audio sync

### ISSUE THREAD

**Issue by KnifeFed** [mdhiggins/PlexAutoSkip#54]
A common issue with Plex clients, at least on Android TV, is that the sound goes out of sync after skipping the intro (on my Nvidia Shield it happens ~50% of the time). This is solved by manually skipping forward/back in the video. It would be awesome if PlexAutoSkip could e.g. skip to a few seconds after the marker initially, then skip back, hopefully mitigating any sync issues.

**Comment by mdhiggins** [comment]
Are you able to test using the plex api commands to see if that actually works? If the api that seeks to a specific time doesn't sync I don't know if a second API based skip would necessarily fix it. If it does work then I could try and develop something
