### ISSUE TITLE
Error on Skipping intro on unraid 

### ISSUE THREAD

**Issue by JustNathanGaming** [mdhiggins/PlexAutoSkip#58]
I Keep getting these errors on my unread Docker install is this normal or is there a problem, it did not skip on my tv or phone.

ERROR - BadRequest exception seekPlayerTo, see https://github.com/mdhiggins/PlexAutoSkip/wiki/Troubleshooting
Traceback (most recent call last):
  File "/usr/local/pas/resources/skipper.py", line 243, in seekPlayerTo
    mediaWrapper.seekTo(targetOffset, player)
  File "/usr/local/pas/resources/mediaWrapper.py", line 373, in seekTo
    player.seekTo(offset)
  File "/usr/local/pas/venv/lib/python3.10/site-packages/plexapi/client.py", line 379, in seekTo
    self.sendCommand('playback/seekTo', offset=offset, type=mtype)
  File "/usr/local/pas/venv/lib/python3.10/site-packages/plexapi/client.py", line 234, in sendCommand
    return query(key, headers=headers)
  File "/usr/local/pas/venv/lib/python3.10/site-packages/plexapi/client.py", line 196, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (403) forbidden; http://192.168.0.6:32500/player/playback/seekTo?commandID=1&offset=139251&type=video

**Comment by mdhiggins** [comment]
Did you do any of the stuff in the troubleshooting link that pops up as part of that error message?

**Comment by JustNathanGaming** [comment]
Hello Mdhiggins,

I tried the TroubleShooting page but those did not fix the error here some logs of the error
<img width="1259" alt="image" src="https://github.com/mdhiggins/PlexAutoSkip/assets/30249774/2f4042aa-98c4-47a3-bf7f-95eba4cfb433">

**Comment by mdhiggins** [comment]
This basically means your client API isn't accepting requests and it can fail for a number of reasons. Are you seeing this on all clients?

You definitely have remote control turned on in iOS correct?

Plex app > Gear Icon / Settings > Remote Control > Advertise As Player (must be on)

I have occasionally had iOS bug out and usually restarting the device will get the client API working again, though occasionally an app reinstall might be needed if that doesn't work

Also always good to verify that the IP address that plex is trying to talk to is correct, looks like your local IP for your iPhone is 192.168.0.6, I would verify that's correct

I did just test on my iPhone and everything is working great so iOS definitely still working and supported
