### ISSUE TITLE
ERROR - [Errno -3]

### ISSUE THREAD

**Issue by Whereamnow** [mdhiggins/PlexAutoSkip#61]
I'm not sure what is causing this error. 

2023-10-14 00:28:32 INFO - Connecting to Plex server...
2023-10-14 00:28:33 INFO - Connected to Plex server Core using plex.tv account
2023-10-14 00:28:33 INFO - Skipper initiated and ready
2023-10-14 00:28:38 ERROR - [Errno -3] Try again
2023-10-14 00:28:38 ERROR - [Errno -3] Try again - goodbye
2023-10-14 00:28:39 ERROR - Connection lost
2023-10-14 00:28:44 ERROR - [Errno -3] Try again
2023-10-14 00:28:44 ERROR - [Errno -3] Try again - goodbye
2023-10-14 00:28:45 ERROR - Connection lost
2023-10-14 00:28:45 INFO - Websocket connected

**Comment by mdhiggins** [comment]
Looks like your server is dropping the websocket connection, not sure why that's more a plex api issue, if it ultimately restores the connection and works and this is just a transient error during the initial connecting I wouldn't worry about it

**Comment by Whereamnow** [comment]
the plex log shows 

Request: plaintext connection from 192.168.3.20:62213 rejected because secure connections are required

Request: plaintext connection from 192.168.3.1:62215 rejected because secure connections are required

**Comment by mdhiggins** [comment]
Do you have HTTPS/SSL enabled in PlexAutoSkip?

**Comment by Whereamnow** [comment]
Seems like this happens if I leave the address blank. It eventually connects to the server.

[Server]
address =
ssl = True
port = 32400

if I fill in the address the problem goes away.

**Comment by mdhiggins** [comment]
If you've provided plex.tv credentials it's probably not looking at the address at all, though without logs difficult to say for sure

The heirarchy of how the connections are handled can be seen in server.py

It looks for a username and servername first, if this is present it will try a token first and then password if token is absent or fails

If all that fails, only then does it look for an address/port/token combo

**Comment by mdhiggins** [comment]
Additionally the SSL setting is only applied if you're using an address/port, as the plex.tv credential login requires ssl

**Comment by Whereamnow** [comment]
after restarting, the same issue came back. After the 2 fails attempts, it does eventually connect tho.

**Comment by mdhiggins** [comment]
Figured as much

I think this is essentially a Plex API issue before any of the autoskip code is really run, you might want to wipe your plex cache and restart/update plex server and see if that helps at all

**Comment by Whereamnow** [comment]
Do you mean this caches:

https://support.plex.tv/articles/202967376-clearing-plugin-channel-agent-http-caches/#:~:text=To%20clear%20the%20cache%2C%20you,in%20which%20you're%20interested.&text=Tip!%3A%20In%20most%20cases%2C,good%20idea%20before%20making%20changes.

**Comment by mdhiggins** [comment]
https://www.plexopedia.com/plex-media-server/general/clear-cache/

Plex has a few areas where it caches things
