### ISSUE TITLE
Is there a way to disable the auto skip if I press back or rewind?

### ISSUE THREAD

**Issue by Deihmos** [mdhiggins/PlexAutoSkip#66]
I have been reading the documents but couldn't find a solution. If the commercial tag includes a part of the show and I want to rewind it will always skip again. The only solution I could find is disabling the advertise as player to prevent it from skipping. 

Is there a way to disable the skip if I rewind?

**Comment by mdhiggins** [comment]
Nope, really no way to handle that, the script can't tell if you rewind back into the window of a skip after exiting it the skip will trigger again

That being said plex has added this functionality natively so you may not need to worry about this anymore

**Comment by Deihmos** [comment]
Ok thanks. Yes, they added it natively for most devices but the Apple TV. I also have an Nvidia shield but live tv doesn’t work well with it.
