### ISSUE TITLE
Does it work with Infuse player?

### ISSUE THREAD

**Issue by morgan-256** [mdhiggins/PlexAutoSkip#68]
Hi, thanks for creating an awesome addon for Plex

I use Infuse player on Apple TV and it doesn't seem to work. I'm guessing it's due to it not "advertising as player" like official Plex apps but would like to confirm. I can't find anything online, even in Infuse's forums

Thanks

**Comment by mdhiggins** [comment]
You are correct, infuse is a custom player that does not implement Plex Companion and therefore cannot be controlled via the API
