### ISSUE TITLE
[FR]: Option to not auto-skip on S01E01

### ISSUE THREAD

**Issue by KnifeFed** [mdhiggins/PlexAutoSkip#7]
When I start watching a whole new show from the start, I want to watch the intro the very first time it's played, so it would be nice if that could be an option.

**Comment by mdhiggins** [comment]
Easy enough to add

42171e0bb4c18aa2179ee0d6eba6330f863cce0a

Included new options under the `[Skip]` section of config.ini to skip intros in the first episode of a series or of a season which is set to `True` by default, set to `False` to ignore these episodes

Wiki updated

Close out if this works for you

Run the script once and these options will be auto added to your config or you can copy them from the updated sample (after updating from Github)

**Comment by KnifeFed** [comment]
Wow, that was fast! Works great, thanks!
