### ISSUE TITLE
Connects to server, but than nothing...

### ISSUE THREAD

**Issue by aibradford** [mdhiggins/PlexAutoSkip#71]
I just set up and have it running through docker, however when i run it nothing happens. It seems to connect to the server fine, but nothing once it connects and never detects any devices running.

can anyone assist?

`

> _2024-07-21 09:56:39 plexautoskip  | To support LSIO projects visit:
> 2024-07-21 09:56:39 plexautoskip  | https://www.linuxserver.io/donate/
> 2024-07-21 09:56:39 plexautoskip  | 
> 2024-07-21 09:56:39 plexautoskip  | ───────────────────────────────────────
> 2024-07-21 09:56:39 plexautoskip  | GID/UID
> 2024-07-21 09:56:39 plexautoskip  | ───────────────────────────────────────
> 2024-07-21 09:56:39 plexautoskip  | 
> 2024-07-21 09:56:39 plexautoskip  | User UID:    1000
> 2024-07-21 09:56:39 plexautoskip  | User GID:    1000
> 2024-07-21 09:56:39 plexautoskip  | ───────────────────────────────────────
> 2024-07-21 09:56:39 plexautoskip  | 
> 2024-07-21 09:56:39 plexautoskip  | 
> 2024-07-21 09:56:39 plexautoskip  | ╔════════════════════════════════════════════════════╗
> 2024-07-21 09:56:39 plexautoskip  | ╠════════════════════════════════════════════════════╣
> 2024-07-21 09:56:39 plexautoskip  | ║                                                    ║
> 2024-07-21 09:56:39 plexautoskip  | ║             This image is deprecated.              ║
> 2024-07-21 09:56:39 plexautoskip  | ║      We will not offer support for this image      ║
> 2024-07-21 09:56:39 plexautoskip  | ║            and it will not be updated.             ║
> 2024-07-21 09:56:39 plexautoskip  | ║                                                    ║
> 2024-07-21 09:56:39 plexautoskip  | ╠════════════════════════════════════════════════════╣
> 2024-07-21 09:56:39 plexautoskip  | ╚════════════════════════════════════════════════════╝
> 2024-07-21 09:56:39 plexautoskip  | 
> 2024-07-21 09:56:39 plexautoskip  | We recommend switching to a newer tag
> 2024-07-21 09:56:39 plexautoskip  | 
> 2024-07-21 09:56:39 plexautoskip  | 
> 2024-07-21 09:56:39 plexautoskip  | ══════════════════════════════════════════════════════
> 2024-07-21 09:56:39 plexautoskip  | [custom-init] No custom files found, skipping...
> 2024-07-21 09:56:39 plexautoskip  | [ls.io-init] done.
> 2024-07-21 09:56:40 plexautoskip  | INFO - /usr/local/pas/venv/bin/python3
> 2024-07-21 09:56:40 plexautoskip  | INFO - Loading config file /usr/local/pas/config/config.ini.
> 2024-07-21 09:56:40 plexautoskip  | INFO - Loading custom JSON file /usr/local/pas/config/custom.json
> 2024-07-21 09:56:40 plexautoskip  | INFO - Connecting to Plex server...
> 2024-07-21 09:56:40 plexautoskip  | INFO - Connected to Plex server Bradflix using plex.tv account
> 2024-07-21 09:56:40 plexautoskip  | INFO - Skipper initiated and ready
> 2024-07-21 09:56:40 plexautoskip  | INFO - Websocket connected_

`

Sorry, i know this is not very helpful information to explain the situation, but as the logs dont show anything, i have no way of knowing what the issue might be?

config.ini below: 

> [Plex.tv]
username = aibradford
password = 
token = ***************
servername = Bradflix

[Server]
address = localhost
ssl = False
port = 32400

[Security]
ignore-certs = False

[Skip]
mode = skip
tags = intro, commercial, advertisement, credits
types = movie, episode
ignored-libraries = 
last-chapter = 0.9
unwatched = True
first-episode-series = Always
first-episode-season = Always
first-safe-tags = 
last-episode-series = Always
last-episode-season = Always
last-safe-tags = 
next = False

[Binge]
ignore-skip-for = 0
safe-tags = 
same-show-only = False
skip-next-max = 0

[Offsets]
start = 2000
end = 1000
command = 500
tags = intro

[Volume]
low = 0
high = 100

>

**Comment by mdhiggins** [comment]
Do your shows have the intro actually tagged? Might need to turn on debug logging to check if it’s seeing playback sessions but if there aren’t any tags in the XML data in Plex it won’t have anything to skip

**Comment by aibradford** [comment]
Yes, the vast majority of them have tags. It still comes up with the skip intro button, but never actually skips it.

How do I enable debug logging?

**Comment by mdhiggins** [comment]
Its in the wiki

https://github.com/mdhiggins/PlexAutoSkip/wiki/Debug-Level-Logging

You might want to post an XML sample as well of one of the episodes that's not working just for review
