### ISSUE TITLE
AlertListener error detected, you may need to update your version of PlexAPI

### ISSUE THREAD

**Issue by Shaunieboy** [mdhiggins/PlexAutoSkip#8]
Just finished setting this up but it keeps repeatedly saying

``ERROR - AlertListener error detected, you may need to update your version of PlexAPI, attempting backwards compatibility``

I tried using a fresh browser to sign into plex to get the API token and I've tested the API key on other programs that work fine

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/PlexAutoSkip/issues/2

You just need to update your plexAPI python package

**Comment by Shaunieboy** [comment]
I tried to update it but I kept getting the same error. I deleted all the requirements and installed them again, I now get this issue
```
INFO - /usr/bin/python3
INFO - Loading config file /opt/plexautoskip/config/config.ini.
INFO - Loading custom JSON file /opt/plexautoskip/config/custom.json
INFO - Connected to Plex server using plex.tv account
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    intro_skipper.start(sslopt=sslopt)
  File "/opt/plexautoskip/resources/introSkipper.py", line 88, in start
    self.start(sslopt)
  File "/opt/plexautoskip/resources/introSkipper.py", line 88, in start
    self.start(sslopt)
  File "/opt/plexautoskip/resources/introSkipper.py", line 88, in start
    self.start(sslopt)
  [Previous line repeated 987 more times]
  File "/opt/plexautoskip/resources/introSkipper.py", line 74, in start
    self.listener = SSLAlertListener(self.server, self.processAlert, self.error, sslopt=sslopt, logger=self.log)
  File "/opt/plexautoskip/resources/sslAlertListener.py", line 23, in __init__
    super(SSLAlertListener, self).__init__(server, callback, callbackError)
  File "/usr/local/lib/python3.8/dist-packages/plexapi/alert.py", line 39, in __init__
    super(AlertListener, self).__init__()
  File "/usr/lib/python3.8/threading.py", line 799, in __init__
    self._started = Event()
  File "/usr/lib/python3.8/threading.py", line 506, in __init__
    self._cond = Condition(Lock())
  File "/usr/lib/python3.8/threading.py", line 233, in __init__
    self._release_save = lock._release_save
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by mdhiggins** [comment]
Hm not sure what happened here but looks like the PlexAPI is failing to start now, the first error is just a minor one that otherwise could have been ignored (they updated the PlexAPI python script, and it should have been able to recover). I think you need to just wipe everything out and install fresh not sure what broke here I haven't ever encountered this specific error before.

**Comment by mdhiggins** [comment]
Also make sure you installed `websocket-client` and not `websockets` as I've seen some of the functions overlap and cause errors, might be worth uninstalling `websockets` if installed as well to see if that helps

Feel free to post some examples of the commands you're running to try and do some of these updates and what versions of the packages you currently have installed so I can try and better help you

I just updated everything on my test machine (plexapi-4.9.2, websocket-client 1.2.3) and not having any issues

**Comment by Shaunieboy** [comment]
Ah, ``websocket-client`` wasn't installed.
quite strange since I ran ``pip -R install ./setup/requirements.txt``. Well it works perfectly fine now, thanks :D
