### ISSUE TITLE
Allow setting offset per show

### ISSUE THREAD

**Issue by KibosJ** [mdhiggins/PlexAutoSkip#9]
Thanks for this project, it's working great.

It would be great if it were possible to set the offset per show rather than globally, Plex seems to pick up the intro on one of my shows a little too early

**Comment by mdhiggins** [comment]
8a43af05685dd2adc8428515d8fa7f66110997ed

That should do the trick, I'll update the wiki if you can confirm this is working on your end but looking good on my tests

Works the same way the custom markers are defined in custom.json, example excerpt here

```json
    "offsets": {
        "29": {
            "start": 5000,
            "end": 2000
        },
        "1996": {
            "start": 6000,
            "end": 3000
        }
    }
```

You can use ratingKey, parentRatingKey, or grandparentRatingKey, the most specific one will be the offset applied

The docker containers will take a little time to update but you can manually pull from github to test

**Comment by mdhiggins** [comment]
Updated the wiki anyway

**Comment by KibosJ** [comment]
I've used the grandparentRatingKey and I'm getting the following error:

`ERROR - Unexpected error getting data from session alert
Traceback (most recent call last):
  File "/usr/local/pas/resources/introSkipper.py", line 177, in processAlert
    wrapper = MediaWrapper(media, self.server, tags=self.settings.tags, custom=self.customEntries, logger=self.log)
  File "/usr/local/pas/resources/mediaWrapper.py", line 84, in __init__
    self.leftOffset = custom.offsets[str(self.media.grandparentRatingKey)].get(STARTKEY, self.leftOffset)
AttributeError: 'list' object has no attribute 'get'
ERROR - Unexpected error getting data from session alert
Traceback (most recent call last):
  File "/usr/local/pas/resources/introSkipper.py", line 177, in processAlert
    wrapper = MediaWrapper(media, self.server, tags=self.settings.tags, custom=self.customEntries, logger=self.log)
  File "/usr/local/pas/resources/mediaWrapper.py", line 84, in __init__
    self.leftOffset = custom.offsets[str(self.media.grandparentRatingKey)].get(STARTKEY, self.leftOffset)
AttributeError: 'list' object has no attribute 'get'`

**Comment by mdhiggins** [comment]
Can you post your custom.json?

**Comment by KibosJ** [comment]
[custom.json.txt](https://github.com/mdhiggins/PlexAutoSkip/files/8200171/custom.json.txt)

```{
  "markers": {},
  "allowed": {
    "users": [],
    "clients": [],
    "keys": []
  },
  "blocked": {
    "users": [],
    "clients": [],
    "keys": []
  },
  "clients": {},
  "offsets": {
    "2122": [
      {
        "start": 5000,
        "end": 1000
      }
    ]
  }
}

**Comment by mdhiggins** [comment]
This might be my bad, I copy/pasted too much from the wiki, though the sample I had posted above was still accurate. The offsets should be dicts only, not an array followed by a dict like the markers since you can only have pair of offsets

Fixed the wiki

Correct version here

```json
{
  "markers": {},
  "allowed": {
    "users": [],
    "clients": [],
    "keys": []
  },
  "blocked": {
    "users": [],
    "clients": [],
    "keys": []
  },
  "clients": {},
  "offsets": {
    "2122": {
      "start": 5000,
      "end": 1000
    }
  }
}
```

**Comment by KibosJ** [comment]
Working now 🙂 thank you very much!
